version: "2"
services:
  master:
    image: "master_image"
    ports:
      - "3001:3001"
    # Created below two lines for keeping container alive
    tty: true
    stdin_open: true
  worker1:
    image: "worker_image"
    ports:
      - "3002:3002"
    network_mode: "host"
    healthcheck:
      interval: 5s
      retries: 5
    tty: true
    stdin_open: true
  worker2:
    image: "worker_image"
    ports:
      - "3003:3002"
    network_mode: "host"
    healthcheck:
      interval: 5s
      retries: 5
    tty: true
    stdin_open: true
